---
application:
  name: "hm-server"
  project: "hospital-management"
  organization: "QoveryCommunity"
routers:
- name: "main-hm-server"
  routes:
  - application_name: "hm-server"
    paths:
    - "/*"
